---
- group:
    name: "{{ redis.group }}"
    state: present
    gid: "{{ redis.process_gid }}"

- user:
    name: "{{ redis.user }}"
    comment: "Nextcloud user"
    uid: "{{ redis.process_uid }}"
    group: "{{ redis.group }}"
    shell: /sbin/nologin

- file: path={{ redis.data_path }} state=directory mode=0770 owner={{ redis.user }} group={{ redis.group }} recurse=true

- name: redis in docker
  docker_container:
    name: "{{ redis.hostname }}"
    hostname: "{{ redis.hostname }}"
    image: redis:latest
    state: started
    restart_policy: always
    pull: true
    purge_networks: yes
    command: "redis-server --appendonly yes"
    networks:
      - name: "{{ redis.network_name }}"
        ipv4_address: "{{ redis.ipaddr }}"
    log_driver: syslog
    user: "{{ redis.process_uid }}"
    groups: "{{ redis.process_gid }}"
    log_opt:
      tag: "redis"
    env:
      TZ: "Europe/Madrid"
    volumes:
      - "{{ redis.data_path }}:/data"
