---
# coredns version and checksum configuration.
coredns_version: "1.8.6"

coredns_config: "/etc/coredns"
coredns_dir: "coredns_{{ coredns_version }}_linux_{{ host_golang_arch }}"
coredns_tmp: "/tmp/coredns"
coredns_url: "https://github.com/coredns/coredns/releases/download/v{{ coredns_version }}/{{ coredns_dir }}.tgz"
coredns_tgz: "/tmp/coredns.tar.gz"

# Forwarder
use_google: false
use_cloudflare: false
use_nextdns: true

