---
# coredns version and checksum configuration.
coredns_version: "1.6.9"
coredns_sha256: "84f437bc8e270a9a309a807db40032250f5efb9e399cea3a66ba95f46d5fb6a9"

coredns_config: "/etc/coredns"
coredns_dir: "coredns_{{ coredns_version }}_linux_amd64"
coredns_tmp: "/tmp/coredns"
coredns_url: "https://github.com/coredns/coredns/releases/download/v{{ coredns_version }}/{{ coredns_dir }}.tgz"
coredns_tgz: "/tmp/coredns.tar.gz"

# Internal DNS
internal_dns:
  - ip: "192.168.79.1"
    host: "edge-router"
  - ip: "192.168.79.6"
    host: "anton"
  - ip: "192.168.79.6"
    host: "grafana"
  - ip: "192.168.79.6"
    host: "coredns"
  - ip: "192.168.79.6"
    host: "monitor"
  - ip: "192.168.79.5"
    host: "attic-sw"
  - ip: "192.168.79.7"
    host: "minerva"
  - ip: "192.168.79.11"
    host: "attic-ap"
  - ip: "192.168.79.12"
    host: "livingroom-ap"
