---
- file: path={{ grafana.conf_path }} state=directory mode=0777 owner={{ grafana.process_uid }} recurse=true
- file: path={{ grafana.lib_path }} state=directory mode=0777 owner={{ grafana.process_uid }} recurse=true


- name: Create user for grafana
  user:
    name: "grafana"
    comment: "User for grafana"
    uid: "{{ grafana.process_uid }}"
    group: "{{ grafana.process_gid }}"
    shell: /sbin/nologin

- name: Grafana frontend for metrics (Docker)
  docker_container:
    name: "{{ grafana.hostname }}"
    hostname: "{{ grafana.hostname }}"
    image: grafana/grafana:6.7.1-ubuntu
    state: started
    restart_policy: always
    pull: true
    purge_networks: yes
    networks:
      - name: "{{ grafana.network_name }}"
        ipv4_address: "{{ grafana.ipaddr }}"
    log_driver: syslog
    log_opt:
      tag: "grafana"
    user: "{{ grafana.process_uid }}"
    groups: "{{ grafana.process_gid }}"
    env:
      TZ: "Europe/Madrid"
      GF_SERVER_DOMAIN: "grafana.etellez.net"
      GF_SERVER_ROOT_URL: "https://grafana.etellez.net/"
      GF_DISABLE_LOGIN_FORM: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "false"
    volumes:
        #- "{{ grafana.conf_path }}:/etc/grafana"
      - "{{ grafana.lib_path }}:/var/lib/grafana"
