---
shadowsocks_dependencies:
  - python-gevent
  - python-m2crypto
  - python-pip
  - qrencode

shadowsocks_location: "/home/shadowsocks"
shadowsocks_password_file: "{{ shadowsocks_location }}/shadowsocks-password.txt"
shadowsocks_qr_code: "{{ shadowsocks_location }}/shadowsocks-qr-code.png"
