---
- file: path={{ radarr.config_path }} state=directory mode=0755 owner={{ transmission.process_uid }} recurse=true
- name: radarr in docker
  docker_container:
    name: "{{ radarr.hostname }}"
    hostname: "{{ radarr.hostname }}"
    image: linuxserver/radarr
    state: started
    restart_policy: always
    pull: true
    purge_networks: yes
    networks:
        - name: "{{ radarr.network_name }}"
          ipv4_address: "{{ radarr.ipaddr }}"
    ports:
        - 7878:7878
    log_driver: syslog
    log_opt:
      tag: "radarr"
    env:
      PUID: "{{ transmission.process_uid }}"
      PGID: "{{ transmission.process_gid }}"
      TZ: "Europe/Madrid"
    volumes:
    - "{{ radarr.config_path }}:/config"
    - "/etc/localtime:/etc/localtime"
    - "{{ plex.movies_path }}:/movies"
    - "{{ plex.movies_es_path }}:/movies-es"
    - "{{ transmission.download_path }}:/downloads"
