---
- group:
   name: "{{ nextcloud.group }}"
   state: present
   gid: "{{ nextcloud.process_gid }}"

- user:
   name: "{{ nextcloud.user }}"
   comment: "Nextcloud user"
   uid: "{{ nextcloud.process_uid }}"
   group: "{{ nextcloud.group }}"
   shell: /sbin/nologin

- file: path={{ nextcloud.config_path }} state=directory mode=0775 owner=www-data group=www-data recurse=true
- file: path={{ nextcloud.base_path }} state=directory mode=0775 owner=www-data group=www-data recurse=true
- file: path={{ nextcloud.data_path }} state=directory mode=0770 owner=www-data group=www-data recurse=true
- file: path={{ nextcloud.php_path }} state=directory mode=0770 owner=www-data group=www-data recurse=true

- name: nextcloud in docker
  docker_container:
    name: "{{ nextcloud.hostname }}"
    hostname: "{{ nextcloud.hostname }}"
    image: nextcloud:21-fpm
    state: started
    restart_policy: always
    pull: true
    purge_networks: true
    networks:
     - name: "{{ nextcloud.network_name }}"
       ipv4_address: "{{ nextcloud.ipaddr }}"
    ports:
      - "9000:9000"
    log_driver: syslog
    log_opt:
     tag: "nextcloud"
    env:
     PID: "{{ nextcloud.process_uid }}"
     GID: "{{ nextcloud.process_gid }}"
     TZ: "Europe/Madrid"
     NEXTCLOUD_UPDATE : "1"
    volumes:
      - "{{ nextcloud.base_path }}:/var/www/html"
      #- "{{ nextcloud.apps_path }}:/var/www/html/custom_apps"
      - "{{ nextcloud.config_path }}:/var/www/html/config"
      - "{{ nextcloud.php_path }}:/usr/local/etc/"
      - "{{ nextcloud.data_path }}:/var/www/html/data"
