---
- name: check if installing a different version of blackbox_exporter
  tags:
    - blackbox_exporter
  shell: "cat {{ blackbox_exporter_config }}/.sha256"
  ignore_errors: true
  register: checksum

- name: determine if blackbox_exporter {{ blackbox_exporter_version}} should be installed
  tags:
    - blackbox_exporter
  set_fact:
    blackbox_exporter_install: (checksum.stdout.find(blackbox_exporter_sha256) == -1) or (blackbox_exporter_force is defined)

- name: download and checksum blackbox_exporter {{ blackbox_exporter_version }} {{ host_golang_arch }} tarball
  tags:
    - blackbox_exporter
  when: blackbox_exporter_install
  get_url:
    url: "{{ blackbox_exporter_url }}"
    dest: "{{ blackbox_exporter_tgz }}"
    checksum: "sha256:{{ blackbox_exporter_sha256 }}"

- name: unpack blackbox_exporter tarball
  tags:
    - blackbox_exporter
  when: blackbox_exporter_install
  unarchive:
    src: "{{ blackbox_exporter_tgz }}"
    dest: "/tmp/"
    copy: false

- name: create blackbox_exporter user
  tags:
    - blackbox_exporter
  when: blackbox_exporter_install
  user:
    name: blackbox_exporter
    shell: "/bin/false"
    comment: "blackbox_exporter service user"

- name: check if blackbox_exporter service exists
  tags:
    - blackbox_exporter
  stat:
    path: "/etc/systemd/system/blackbox_exporter.service"
  register: svccheck

- name: stop blackbox_exporter service if it exists
  tags:
    - blackbox_exporter
  when: svccheck.stat.exists
  service:
    name: blackbox_exporter
    state: stopped

- name: copy blackbox_exporter binary to {{ host_bin_path }}
  tags:
    - blackbox_exporter
  when: blackbox_exporter_install
  command: "cp {{ blackbox_exporter_tmp }}/blackbox_exporter {{ host_bin_path }}/"

- name: set permissions on blackbox_exporter binary
  tags:
    - blackbox_exporter
  when: blackbox_exporter_install
  file:
    path: "{{ host_bin_path }}/blackbox_exporter"
    owner: blackbox_exporter
    group: blackbox_exporter
    mode: 0755

- name: grant capabilities to blackbox_exporter binary
  tags:
    - blackbox_exporter
  capabilities:
    path: "{{ host_bin_path }}/blackbox_exporter"
    capability: "cap_net_raw+ep"
    state: present

- name: create blackbox_exporter config directory
  tags:
    - blackbox_exporter
  when: blackbox_exporter_install
  file:
    path: "{{ blackbox_exporter_config }}"
    state: directory
    owner: blackbox_exporter
    group: blackbox_exporter
    mode: 0755

- name: create blackbox_exporter configuration
  tags:
    - blackbox_exporter
  template:
    src: blackbox_exporter.yml.j2
    dest: "{{ blackbox_exporter_config }}/blackbox_exporter.yml"

- name: create blackbox_exporter systemd unit
  tags:
    - blackbox_exporter
  template:
    src: blackbox_exporter.service.j2
    dest: "/etc/systemd/system/blackbox_exporter.service"

- name: reload systemd configurations
  tags:
    - blackbox_exporter
  command: "systemctl daemon-reload"

- name: start blackbox_exporter service
  tags:
    - blackbox_exporter
  service:
    name: blackbox_exporter
    state: started
    enabled: true

- name: remove temporary blackbox_exporter files
  tags:
    - blackbox_exporter
  when: blackbox_exporter_install
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ blackbox_exporter_tmp }}"
    - "{{ blackbox_exporter_tgz }}"

- name: create checksum file for blackbox_exporter {{ blackbox_exporter_version }}
  tags:
    - blackbox_exporter
  when: blackbox_exporter_install
  template:
    src: sha256.j2
    dest: "{{ blackbox_exporter_config }}/.sha256"
