---
- name: download and checksum snmp_exporter binary
  tags:
    - snmp_exporter
  get_url:
    url: "{{ snmp_exporter_url }}"
    dest: "{{ snmp_exporter_tgz }}"
    checksum: "sha256:{{ snmp_exporter_sha256 }}"

- name: unpack snmp_exporter tarball
  tags:
    - snmp_exporter
  unarchive:
    src: "{{ snmp_exporter_tgz }}"
    dest: "/tmp/"
    copy: false

- name: create snmp_exporter user
  tags:
    - snmp_exporter
  user:
    name: snmp_exporter
    shell: "/bin/false"
    comment: "snmp_exporter service user"

- name: check if snmp_exporter service exists
  tags:
    - snmp_exporter
  stat:
    path: "/etc/systemd/system/snmp_exporter.service"
  register: checked

- name: stop snmp_exporter service if it exists
  tags:
    - snmp_exporter
  when: checked.stat.exists
  service:
    name: snmp_exporter
    state: stopped

- name: copy snmp_exporter binary to {{ host_bin_path }}
  tags:
    - snmp_exporter
  command: "cp /tmp/{{ snmp_exporter_dir }}/snmp_exporter {{ host_bin_path }}/"

- name: set permissions on snmp_exporter binary
  tags:
    - snmp_exporter
  file:
    path: "{{ host_bin_path }}/snmp_exporter"
    owner: snmp_exporter
    group: snmp_exporter
    mode: 0755

- name: create snmp_exporter config directory
  tags:
    - snmp_exporter
  file:
    path: "/etc/snmp_exporter"
    state: directory
    owner: snmp_exporter
    group: snmp_exporter
    mode: 0755

- name: copy snmp.yml to /etc/snmp_exporter
  tags:
    - snmp_exporter
  command: "cp /tmp/{{ snmp_exporter_dir }}/snmp.yml /etc/snmp_exporter/"

- name: create snmp_exporter systemd unit
  tags:
    - snmp_exporter
  template:
    src: snmp_exporter.service.j2
    dest: "/etc/systemd/system/snmp_exporter.service"

- name: reload systemd configurations
  tags:
    - snmp_exporter
  command: "systemctl daemon-reload"

- name: start snmp_exporter service
  tags:
    - snmp_exporter
  service:
    name: snmp_exporter
    state: started
    enabled: true

- name: remove temporary snmp_exporter files
  tags:
    - snmp_exporter
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/tmp/{{ snmp_exporter_dir }}"
    - "{{ snmp_exporter_tgz }}"
