---
- name: Create group for transmission
  group:
    gid: "{{ transmission.process_gid }}"
    name: "{{ transmission.group }}"
    state: present

- name: Create user for transmission
  user:
    name: "{{ transmission.user }}"
    comment: "User for Transmission"
    uid: "{{ transmission.process_uid }}"
    group: "{{ transmission.group }}"
    shell: /sbin/nologin

- file: path={{ transmission.conf_path }} state=directory mode=0755 owner={{ transmission.process_uid }} recurse=true
- file: path={{ transmission.download_path }} state=directory mode=0755 owner={{ transmission.process_uid }} recurse=true
- file: path={{ transmission.watch_path }} state=directory mode=0755 owner={{ transmission.process_uid }} recurse=true

- name: Transmission for torrents
  docker_container:
    name: "{{ transmission.hostname }}"
    hostname: "{{ transmission.hostname }}"
    image: linuxserver/transmission
    state: started
    restart_policy: always
    pull: true
    ports:
      - "{{ transmission.frontend_addr }}:9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    purge_networks: true
    networks:
      - name: "{{ transmission.network_name }}"
        ipv4_address: "{{ transmission.ipaddr }}"
    env:
      PGID: "{{ transmission.process_gid }}"
      PUID: "{{ transmission.process_uid }}"
      TZ: "Europe/Madrid"
    log_driver: syslog
    log_opt:
      tag: "transmission"
    volumes:
      - "{{ transmission.conf_path }}:/config"
      - "{{ transmission.download_path }}:/downloads"
      - "{{ transmission.watch_path }}:/watch"
