---
- file: path={{ mysql.data_path }} state=directory mode=0770 owner={{ mysql.process_uid }} recurse=true
- file: path={{ mysql.conf_path }} state=directory mode=0777 owner={{ mysql.process_uid }} recurse=true

- name: Create MySQL group
  group:
    name: "{{ mysql.group }}"
    state: present
    gid: "{{ mysql.process_gid }}"

- name: Create MySQL user
  user:
    name: "{{ mysql.user }}"
    uid: "{{ mysql.process_uid }}"
    group: "{{ mysql.group }}"
    state: present

- name: mysql in docker
  docker_container:
    name: "{{ mysql.hostname }}"
    hostname: "{{ mysql.hostname }}"
    image: mysql
    state: started
    restart_policy: always
    pull: true
    purge_networks: yes
    networks:
      - name: "{{ mysql.network_name }}"
        ipv4_address: "{{ mysql.ipaddr }}"
    ports:
      - 3306:3306
    log_driver: syslog
    log_opt:
      tag: "mysql"
    env:
      PUID: "{{ mysql.process_uid }}"
      PGID: "{{ mysql.process_gid }}"
      mysql.ROOT_PASSWORD: "{{ mysql.root_password }}"
      TZ: "Europe/Madrid"
    volumes:
      - "{{ mysql.data_path }}:/var/lib/mysql"
      - "{{ mysql.conf_path }}:/etc/mysql/conf.d"

