---

- name: Create group for unifi
  group:
    gid: "{{ unifi.process_gid }}"
    name: "{{ unifi.group }}"
    state: present

- name: Create user for unifi
  user:
    name: "{{ unifi.user }}"
    comment: "User for unifi"
    uid: "{{ unifi.process_uid }}"
    group: "{{ unifi.group }}"
    shell: /sbin/nologin

- file: path={{  unifi.conf_path  }} state=directory mode=0755 owner={{ unifi.process_uid }} recurse=true
- name: Unifi controller container
  docker_container:
    name: "{{ unifi.hostname }}"
    hostname: "{{ unifi.hostname }}"
    image: linuxserver/unifi-controller
    state: started
    restart_policy: always
    pull: true
    ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "8880:8880"
      - "6789:6789"
    purge_networks: yes
    networks:
      - name: "{{ unifi.network_name }}"
        ipv4_address: "{{ unifi.ipaddr }}"
    env:
      PGID: "{{ unifi.process_gid }}"
      PUID: "{{ unifi.process_uid }}"
      TZ: "Europe/Madrid"
    log_driver: syslog
    log_opt:
      tag: "unifi"
    volumes:
      - "{{ unifi.conf_path }}:/config"
