---
- name: download and checksum node_exporter {{ host_golang_arch }} binary
  tags:
    - node_exporter
  get_url:
    url: "{{ node_exporter_url }}"
    dest: "{{ node_exporter_tgz }}"
    checksum: "sha256:{{ node_exporter_sha256 }}"

- name: unpack node_exporter tarball
  tags:
    - node_exporter
  unarchive:
    src: "{{ node_exporter_tgz }}"
    dest: "/tmp/"
    copy: false

- name: create node_exporter user
  tags:
    - node_exporter
  user:
    name: node_exporter
    shell: "/bin/false"
    comment: "node_exporter service user"

- name: check if node_exporter service exists
  tags:
    - node_exporter
  stat:
    path: "/etc/systemd/system/node_exporter.service"
  register: checked

- name: stop node_exporter service if it exists
  tags:
    - node_exporter
  when: checked.stat.exists
  service:
    name: node_exporter
    state: stopped

- name: copy node_exporter binary to {{ host_bin_path }}
  tags:
    - node_exporter
  command: "cp /tmp/{{ node_exporter_dir }}/node_exporter {{ host_bin_path }}/"

- name: set permissions on node_exporter binary
  tags:
    - node_exporter
  file:
    path: "{{ host_bin_path }}/node_exporter"
    owner: node_exporter
    group: node_exporter
    mode: 0755

- name: create node_exporter systemd unit
  tags:
    - node_exporter
  template:
    src: node_exporter.service.j2
    dest: "/etc/systemd/system/node_exporter.service"

- name: reload systemd configurations
  tags:
    - node_exporter
  command: "systemctl daemon-reload"

- name: start node_exporter service
  tags:
    - node_exporter
  service:
    name: node_exporter
    state: started
    enabled: true

- name: remove temporary node_exporter files
  tags:
    - node_exporter
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/tmp/{{ node_exporter_dir }}"
    - "{{ node_exporter_tgz }}"
