---
- file: path={{ sonarr.config_path }} state=directory mode=0755 owner={{ transmission.process_uid }} recurse=true
- name: sonarr in docker
  docker_container:
    name: "{{ sonarr.hostname }}"
    hostname: "{{ sonarr.hostname }}"
    image: linuxserver/sonarr
    state: started
    restart_policy: always
    pull: true
    purge_networks: yes
    networks:
        - name: "{{ sonarr.network_name }}"
          ipv4_address: "{{ sonarr.ipaddr }}"
    ports:
        - 8989:8989
    log_driver: syslog
    log_opt:
      tag: "sonarr"
    env:
      PUID: "{{ transmission.process_uid }}"
      PGID: "{{ transmission.process_gid }}"
      TZ: "Europe/Madrid"
    volumes:
    - "{{ sonarr.config_path }}:/config"
    - "/etc/localtime:/etc/localtime"
    - "{{ plex.tvshows_path }}:/tv"
    - "{{ plex.tvshows_es_path }}:/tv-es"
    - "{{ tranmission.download_path }}:/downloads"
