---
# Prometheus version and checksum configuration.
prometheus_version: "2.15.2"
prometheus_sha256: "579f800ec3ec2dc9a36d2d513e7800552cf6b0898f87a8abafd54e73b53f8ad0"
# Prometheus alerting configuration.
prometheus_alertmanagers:
  - "anton:9093"
# Prometheus jobs configuration.
prometheus_jobs:
  - job: "apcupsd"
    targets:
      - "minerva:9162"
  - job: "node"
    targets:
      - "anton:9100"
      - "minerva:9100"
      - "milhouse.dub.home:9100"
  - job: "prometheus"
    scrape_interval: "5s"
    targets:
      - "anton:9090"
  - job: "snmp"
    path: "/snmp"
    params:
      module: [if_mib]
    targets:
      - "edge-router.dub.home"
      - "livingroom-ap.dub.home"
      - "office-ap.dub.home"
      - "core-sw.dub.home"
      - "utility-sw.dub.home"
      - "edge-router.mad.home"
      - "attic-ap.mad.home"
      - "livingroom-ap.mad.home"
    relabel_target: "anton:9116"
  - job: "blackbox_http_2xx_grafana"
    path: "/probe"
    params:
      module: [http_2xx]
    targets:
      - "https://grafana.etellez.net"
    relabel_target: "anton:9115"
  - job: "blackbox_http_2xx_sonarr"
    path: "/probe"
    params:
      module: [http_2xx]
    targets:
      - "https://sonarr.etellez.net"
    relabel_target: "anton:9115"
  - job: "blackbox_http_2xx_radarr"
    path: "/probe"
    params:
      module: [http_2xx]
    targets:
      - "https://radarr.etellez.net"
    relabel_target: "anton:9115"
  - job: "blackbox_http_2xx_torrent"
    path: "/probe"
    params:
      module: [http_2xx]
    targets:
      - "https://donkey.etellez.net"
    relabel_target: "anton:9115"
  - job: "blackbox_http_401_nextcloud"
    path: "/probe"
    params:
      module: [http_401]
    targets:
      - "https://files.etellez.net/f/119518"
    relabel_target: "anton:9115"
  - job: "blackbox_http_401_prometheus"
    path: "/probe"
    params:
      module: [http_401]
    targets:
      - "https://prometheus.etellez.net"
    relabel_target: "anton:9115"
  - job: "blackbox_ssh"
    scrape_interval: "1m"
    path: "/probe"
    params:
      module: [ssh_banner]
    targets:
      - "milhouse.dub.home:22"
      - "mad.etellez.net:22"
      - "minerva:22"
    relabel_target: "anton:9115"
  - job: "blackbox_mysql"
    scrape_interval: "1m"
    path: "/probe"
    params:
      module: [tcp_connect]
    targets:
      - "minerva:3306"
    relabel_target: "anton:9115"
  - job: "blackbox_exporter"
    targets:
      - "anton:9115"
  - job: blackbox-ping
    path: /probe
    params:
      module: [icmp]
    targets:
      - 8.8.8.8 # Google DNS
      - 1.1.1.1 # CF DNS
      - 45.90.28.152 # NextDNS
      - ipv4-c012-mad001-ix.1.oca.nflxvideo.net # Netflix MAD
      - ipv4-c011-mad002-telefonicaes-isp.1.oca.nflxvideo.net # Netflix OCA Telefonica
      - ipv4-c035-mad001-ix.1.oca.nflxvideo.net # Netflix MAD
      - mad07s09-in-f3.1e100.net # Google Edge - MAD
      - minerva
      - dub.etellez.net # DUB via public internet
      - attic-ap
      - livingroom-ap
      - 192.168.1.1 # MAD-DUB edge-router.dub via wireguard
      - 192.168.30.6 # DUB-MAD edge-router.dub via wireguard
    relabel_target: "anton:9115"
  - job: "coredns"
    targets:
      - "anton:9153"
      - "milhouse.dub.home:9153"
prometheus_config: "/etc/prometheus"
prometheus_data: "/var/lib/prometheus"
prometheus_external_url: "https://prometheus.etellez.net"
prometheus_dir: "prometheus-{{ prometheus_version }}.linux-amd64"
prometheus_tmp: "/tmp/{{ prometheus_dir }}"
prometheus_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/{{ prometheus_dir }}.tar.gz"
prometheus_tgz: "/tmp/prometheus.tar.gz"
