---
- name: Create + permissions for Plex transcode
  file: path={{ plex.transcode_path }} state=directory mode=0755 owner={{ transmission.process_uid }} recurse=true
- name: Create + permissions for Plex config path
  file: path={{ plex.config_path }} state=directory mode=0755 owner={{ transmission.process_uid }} recurse=true
- name: Create + permissions for Plex Movies ES
  file: path={{ plex.movies_es_path }} state=directory mode=0755 owner={{ transmission.process_uid }} recurse=true
- name: Create + permissions for Plex Movies
  file: path={{ plex.movies_path }} state=directory mode=0755 owner={{ transmission.process_uid }} recurse=true
- name: Create + permissions for Plex Shows
  file: path={{ plex.shows_path }} state=directory mode=0755 owner={{ transmission.process_uid }} recurse=true
- name: Create + permissions for Plex Shows ES
  file: path={{ plex.shows_es_path }} state=directory mode=0755 owner={{ transmission.process_uid }} recurse=true
- name: Create + permissions for Plex Library
  command: "chown -R {{ transmission.process_uid }}:{{ transmission.process_gid }} {{ plex.library_path }}"
  changed_when: false

- name: Add Plex GPG key for package
  apt_key:
    url: https://downloads.plex.tv/plex-keys/PlexSign.key
    state: present

- name: Add Plex Repository
  apt_repository:
    repo: deb https://downloads.plex.tv/repo/deb public main
    state: present

- name: Update apt and install plexmediaserver
  apt: update_cache=yes name=plexmediaserver state=latest

- name: Update systemd user from plex to torrent
  replace:
    path: /lib/systemd/system/plexmediaserver.service
    regexp: "User=plex"
    replace: "User=torrent"

- name: Update systemd group from plex to torrent
  replace:
    path: /lib/systemd/system/plexmediaserver.service
    regexp: "Group=plex"
    replace: "Group=torrent"

- name: symlink library to ZFS stored lib
  file:
    dest: "/var/lib/plexmediaserver/Library/Application Support"
    src: "/storage/plex/library/Library/Application Support/"
    owner: torrent
    group: torrent
    state: link

- name: Reload plexmediaserver + daemon reload to pickup changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: plexmediaserver
