---
- name: Create + permissions for Plex transcode
  file: path={{ plex.transcode_path }} state=directory mode=0755 owner={{ transmission.process_uid }} recurse=true
- name: Create + permissions for Plex config path
  file: path={{ plex.config_path }} state=directory mode=0755 owner={{ transmission.process_uid }} recurse=true
- name: Create + permissions for Plex Movies ES
  file: path={{ plex.movies_es_path }} state=directory mode=0755 owner={{ transmission.process_uid }} recurse=true
- name: Create + permissions for Plex Movies
  file: path={{ plex.movies_path }} state=directory mode=0755 owner={{ transmission.process_uid }} recurse=true
- name: Create + permissions for Plex Shows
  file: path={{ plex.shows_path }} state=directory mode=0755 owner={{ transmission.process_uid }} recurse=true
- name: Create + permissions for Plex Shows ES
  file: path={{ plex.shows_es_path }} state=directory mode=0755 owner={{ transmission.process_uid }} recurse=true
- name: Create + permissions for Plex Library
  file: path={{ plex.library_path }} state=directory mode=0755 owner=plex recurse=true

- name: Add Plex GPG key for package
  apt_key:
    url: https://downloads.plex.tv/plex-keys/PlexSign.key
    state: present

- name: Add Plex Repository
  apt_repository:
    repo: deb https://downloads.plex.tv/repo/deb public main
    state: present

- name: Update apt and install plexmediaserver
  apt: update_cache=yes name=plexmediaserver state=latest

- name: Replace library path in systemd
  replace:
    path: /lib/systemd/system/plexmediaserver.service
    regexp: '/var/lib/plexmediaserver'
    replace: "{{ plex.library_path }}"

- name: Ansible replace string example
  replace:
    path: /lib/systemd/system/plexmediaserver.service
    regexp: '/var/lib/plexmediaserver'
    replace: "{{ plex.library_path }}"

- name: Reload plexmediaserver + daemon reload to pickup changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: plexmediaserver