---
- hosts: server
  tasks:
    - name: Create a group of all hosts by operating system
      group_by: key={{ansible_distribution}}-{{ansible_distribution_version}}

- hosts: anton
  become: true
  roles:
    - wireguard
    - ssl
    - common
    - ssh
    - coredns
    - hw-monitoring
    - prometheus
    - alertmanager
    - node_exporter
    - snmp_exporter
    - blackbox_exporter
    - docker
    - unifi
    - grafana
    - {
        role: nginx,
        sudo: true,
        nginx_user: "nginx",
        nginx_group: "nginx",
        process_uid: "1035",
        process_gid: "1035",
        tags: ["nginx"],
      }
