---
- hosts: server
  tasks:
    - name: Create a group of all hosts by operating system
      group_by: key={{ansible_distribution}}-{{ansible_distribution_version}}

- hosts: minerva
  become: true
  roles:
    - backups
