---
- hosts: minerva
  become: true
  roles:
    - common
    - ssh
    - hw-monitoring
      #- apcupsd
    - apcupsd_exporter
    - node_exporter
    - docker
    - mysql
    - transmission
    - plex
    - nextcloud
    - redis
    - sonarr
    - radarr
    - prowlarr
    - jackett
    - backups
