---
- hosts: server
  tasks:
    - name: Create a group of all hosts by operating system
      group_by: key={{ansible_distribution}}-{{ansible_distribution_version}}

- hosts: minerva
  become: true
  roles:
    - common
    - ssh
    - hw-monitoring
    - node_exporter
    - docker
    - mysql
    - transmission
    - plex
    - nextcloud
    - {
      role: redis,
      redis_hostname: "nextcloud-redis",
      redis_data_path: "/var/cache/redis",
      ipaddr: "172.16.51.32",
      network_name: "privnet",
      process_uid: 1011,
      process_gid: 1012,
      redis_user: "redis",
      redis_group: "redis",
    }
    - sonarr
    - radarr
