---
- hosts: server
  tasks:
    - name: Create a group of all hosts by operating system
      group_by: key={{ansible_distribution}}-{{ansible_distribution_version}}

- hosts: minerva
  become: true
  roles:
    - common
    - ssh
    - hw-monitoring
    - node_exporter
    - docker
    - mysql
    - transmission
    - plex
    - nextcloud
    - redis
    - sonarr
    - radarr
