---
- hosts: monitor
  tasks:
    - name: Create a group of all hosts by operating system
      group_by: key={{ansible_distribution}}-{{ansible_distribution_version}}

- hosts: monitor
  become: true
  roles:
    - common
    - alertmanager
    - node_exporter
    - blackbox_exporter
    - {
      role: ssh,
      sudo: true,
      ssh_notify_email_to: "relviratellez@gmail.com",
      ssh_notify_email_from: "ops@etellez.net",
      ssh_allow_user: "ret",
      ssh_enable_email_notifications: false,
      tags: ['ssh']
    }
