---
shadowsocks_server: "{{ ansible_eth0.ipv4.address }}"
shadowsocks_server_port: "7979"
shadowsocks_local_port: "1080"
shadowsocks_timeout: "600"
shadowsocks_encryption_method: "aes-256-cfb"

shadowsocks_dependencies:
  - python-gevent
  - python-m2crypto
  - python-pip
  - qrencode

shadowsocks_user: "shadowsocks"
shadowsocks_group: "shadowsocks"
shadowsocks_location: "/home/shadowsocks"
shadowsocks_log_file: "/var/log/shadowsocks.log"
shadowsocks_pid_file: "/var/run/shadowsocks.pid"
shadowsocks_password_file: "{{ shadowsocks_location }}/shadowsocks-password.txt"
shadowsocks_qr_code: "{{ shadowsocks_location }}/shadowsocks-qr-code.png"
