---
- name: install packages required for wireguard
  tags:
    - wireguard
  apt:
    pkg: ['wireguard', 'wireguard-tools']

- name: create systemd service for re-resolver script
  tags:
    - wireguard
  template:
    src: wireguard_reresolve-dns.service.j2
    dest: "/etc/systemd/system/wireguard_reresolve-dns.service"
    owner: root
    group: root
    mode: "0775"

- name: create timer for re-resolver script
  tags:
    - wireguard
  template:
    src: wireguard_reresolve-dns.timer.j2
    dest: "/etc/systemd/system/wireguard_reresolve-dns.timer"
    owner: root
    group: root
    mode: "0775"

- name: enable and start timer for wireguard_reresolve-dns
  systemd:
    name: wireguard_reresolve-dns.timer
    state: started
    enabled: True
